package com.ljy.entity;

import java.io.Serializable;

/**
 * @类名: com.ljy.entity
 * @作者:
 * @创建时间: 2019-12-02 20:04
 * @描述:
 **/
public class Student implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuid
     *
     * @mbg.generated Mon Dec 02 11:45:51 CST 2019
     */
    private Integer stuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuname
     *
     * @mbg.generated Mon Dec 02 11:45:51 CST 2019
     */
    private String stuname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.clazzid
     *
     * @mbg.generated Mon Dec 02 11:45:51 CST 2019
     */
    private Integer clazzid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.age
     *
     * @mbg.generated Mon Dec 02 11:45:51 CST 2019
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sex
     *
     * @mbg.generated Mon Dec 02 11:45:51 CST 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.birth
     *
     * @mbg.generated Mon Dec 02 11:45:51 CST 2019
     */
    private String birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbg.generated Mon Dec 02 11:45:51 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuid
     *
     * @return the value of student.stuid
     *
     * @mbg.generated Mon Dec 02 11:45:51 CST 2019
     */
    public Integer getStuid() {
        return stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuid
     *
     * @param stuid the value for student.stuid
     *
     * @mbg.generated Mon Dec 02 11:45:51 CST 2019
     */
    public void setStuid(Integer stuid) {
        this.stuid = stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuname
     *
     * @return the value of student.stuname
     *
     * @mbg.generated Mon Dec 02 11:45:51 CST 2019
     */
    public String getStuname() {
        return stuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuname
     *
     * @param stuname the value for student.stuname
     *
     * @mbg.generated Mon Dec 02 11:45:51 CST 2019
     */
    public void setStuname(String stuname) {
        this.stuname = stuname == null ? null : stuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.clazzid
     *
     * @return the value of student.clazzid
     *
     * @mbg.generated Mon Dec 02 11:45:51 CST 2019
     */
    public Integer getClazzid() {
        return clazzid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.clazzid
     *
     * @param clazzid the value for student.clazzid
     *
     * @mbg.generated Mon Dec 02 11:45:51 CST 2019
     */
    public void setClazzid(Integer clazzid) {
        this.clazzid = clazzid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.age
     *
     * @return the value of student.age
     *
     * @mbg.generated Mon Dec 02 11:45:51 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.age
     *
     * @param age the value for student.age
     *
     * @mbg.generated Mon Dec 02 11:45:51 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sex
     *
     * @return the value of student.sex
     *
     * @mbg.generated Mon Dec 02 11:45:51 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sex
     *
     * @param sex the value for student.sex
     *
     * @mbg.generated Mon Dec 02 11:45:51 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.birth
     *
     * @return the value of student.birth
     *
     * @mbg.generated Mon Dec 02 11:45:51 CST 2019
     */
    public String getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.birth
     *
     * @param birth the value for student.birth
     *
     * @mbg.generated Mon Dec 02 11:45:51 CST 2019
     */
    public void setBirth(String birth) {
        this.birth = birth == null ? null : birth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Dec 02 11:45:51 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", stuid=").append(stuid);
        sb.append(", stuname=").append(stuname);
        sb.append(", clazzid=").append(clazzid);
        sb.append(", age=").append(age);
        sb.append(", sex=").append(sex);
        sb.append(", birth=").append(birth);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
